// Generated from rust/src/currency.rs (CURRENCIES). Do not edit by hand.
// Regenerate (PowerShell): $env:UPDATE_CURRENCY_CATALOG = '1'; cargo test -p codexbar currency_catalog
export const CURRENCY_CATALOG = [
  { code: "USD", symbol: "$", fallbackRate: 1 },
  { code: "GBP", symbol: "£", fallbackRate: 0.79 },
  { code: "EUR", symbol: "€", fallbackRate: 0.92 },
  { code: "CZK", symbol: "Kč", fallbackRate: 21 },
  { code: "CNY", symbol: "¥", fallbackRate: 7.27 },
  { code: "JPY", symbol: "¥", fallbackRate: 154 },
  { code: "KRW", symbol: "₩", fallbackRate: 1428.9 },
  { code: "CAD", symbol: "$", fallbackRate: 1.38 },
  { code: "AUD", symbol: "$", fallbackRate: 1.55 },
  { code: "HKD", symbol: "$", fallbackRate: 7.8 },
  { code: "TWD", symbol: "NT$", fallbackRate: 32.3 },
  { code: "SGD", symbol: "$", fallbackRate: 1.34 },
  { code: "INR", symbol: "₹", fallbackRate: 84.5 },
  { code: "CHF", symbol: "Fr.", fallbackRate: 0.8 },
  { code: "AED", symbol: "د.إ", fallbackRate: 3.6725 },
  { code: "TRY", symbol: "₺", fallbackRate: 48.5 },
  { code: "NZD", symbol: "$", fallbackRate: 1.761 },
  { code: "SEK", symbol: "kr", fallbackRate: 9.908 },
  { code: "NOK", symbol: "kr", fallbackRate: 9.48 },
  { code: "DKK", symbol: "kr", fallbackRate: 6.554 },
  { code: "PLN", symbol: "zł", fallbackRate: 3.838 },
  { code: "BRL", symbol: "R$", fallbackRate: 5.117 },
  { code: "MXN", symbol: "$", fallbackRate: 17.47 },
  { code: "ZAR", symbol: "R", fallbackRate: 16.36 },
  { code: "THB", symbol: "฿", fallbackRate: 33.37 },
  { code: "IDR", symbol: "Rp", fallbackRate: 17836 },
  { code: "VND", symbol: "₫", fallbackRate: 25962 },
  { code: "UAH", symbol: "₴", fallbackRate: 44.86 },
] as const;
